FROM apache/spark:3.5.0

# Creating a dockerfile for apache spark to import all necessary files for integrations

USER root

# =========================
# Hadoop AWS
# =========================
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    -P /opt/spark/jars/

# =========================
# AWS SDK Bundle
# More stable with Hadoop 3.3.4
# =========================
RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar \
    -P /opt/spark/jars/

# =========================
# PostgreSQL JDBC
# =========================
RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.jar \
    -P /opt/spark/jars/